//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UBIT.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class MedicalRecord
    {
        public int mrecord_id { get; set; }
        public int mrecord_patient_id { get; set; }
        public string mrecord_patient_problem { get; set; }
        public System.DateTime mrecord_dateofExamintion { get; set; }
    
        public virtual Patient Patient { get; set; }
    }
}
